name: Soroban Contracts CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'contracts/**'
      # Adjust these paths if your toml files are inside the contracts folder:
      - 'contracts/Cargo.toml'
      - 'contracts/Cargo.lock'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'contracts/**'
      - 'contracts/Cargo.toml'
      - 'contracts/Cargo.lock'

env:
  CARGO_TERM_COLOR: always

jobs:
  # Rust Smart Contracts Job
  rust-test-and-build:
    name: Rust Test and Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./contracts
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32v1-none

      - name: Rust Cache (Speed Optimization)
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "contracts -> target"

      - name: Run Unit Tests
        run: cargo test
        working-directory: ./contracts

      - name: Verify WASM Compilation
        run: cargo build --target wasm32v1-none --release
        working-directory: ./contracts